### ISSUE TITLE
Trips type

### ISSUE THREAD

**Issue by AbdelilahTAHIRI** [eron93br/carOBD#1]
Hello @eron93br 

Firstly, thank you for the datasets. I would like to know if the trips in dataset were been in an urban or rural roads ?

Thank you

**Comment by eron93br** [comment]
Hi @AbdelilahTAHIRI  sorry for the delay answering you. 

- IdleX.csv corresponds to the car with the engine on, but with no movement (speed = 0)
- liveX.csv corresponds to a fixed trip inside urban trajetory
- longX.csv corresponds to highways (freeways) 
- ufpeX.csv corresponds to urban trip (inside university campus)

I hope that this can help you :)

**Comment by AbdelilahTAHIRI** [comment]
Hi @eron93br ,

Thank you so much for the response. it is at the right moment :)

What about driveX.csv? Is it on the rural roads or on freeways also?

**Comment by eron93br** [comment]
Refers to the vehicle in motion mode (speed>0) also in high speed roads.

```
idleX.csv refers to the vehicle in the IDLE mode
driveX.csv refers to the vehicle in motion mode in high speed roads
liveX.csv refers to the vehicle in a specific traject (work --> home)
ufpeX.csv refers to the vehicle in motion mode inside an university campus (low speed)
longX.csv refers to long trips with the vehicle in motion mode.
```

I don't have any record in rural roads :(

**Comment by AbdelilahTAHIRI** [comment]
It's clear for me right now. 
Thank you for your time :)
